version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: tiktok-mysql
    ports:
      - 3306:3306
    volumes:
      - $PWD/docker-compose/data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - center_net

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
    networks:
      - center_net

  redis:
    image: 'bitnami/redis:latest'
    container_name: tiktok-redis
    command: ["redis-server","/etc/redis/redis.conf"] # 密码在这边
    ports:
      - "6379:6379"
    volumes:
      - $PWD/docker-compose/data/redis/data:/data
      - $PWD/docker-compose/conf/redis.conf:/etc/redis/redis.conf
    restart: always
    networks:
      - center_net
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: tiktok-rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - $PWD/docker-compose/data/rabbitmq/data:/var/lib/rabbitmq
      - $PWD/docker-compose/data/rabbitmq/log:/var/log/rabbitmq/log
    restart: always
    networks:
      - center_net

networks:
  center_net:
    external: true