// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: action_service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ActionService service

func NewActionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ActionService service

type ActionService interface {
	FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...client.CallOption) (*DouyinFavoriteActionResponse, error)
	FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...client.CallOption) (*DouyinFavoriteListResponse, error)
	CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...client.CallOption) (*DouyinCommentActionResponse, error)
	CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...client.CallOption) (*DouyinCommentListResponse, error)
}

type actionService struct {
	c    client.Client
	name string
}

func NewActionService(name string, c client.Client) ActionService {
	return &actionService{
		c:    c,
		name: name,
	}
}

func (c *actionService) FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...client.CallOption) (*DouyinFavoriteActionResponse, error) {
	req := c.c.NewRequest(c.name, "ActionService.FavoriteAction", in)
	out := new(DouyinFavoriteActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionService) FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...client.CallOption) (*DouyinFavoriteListResponse, error) {
	req := c.c.NewRequest(c.name, "ActionService.FavoriteList", in)
	out := new(DouyinFavoriteListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionService) CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...client.CallOption) (*DouyinCommentActionResponse, error) {
	req := c.c.NewRequest(c.name, "ActionService.CommentAction", in)
	out := new(DouyinCommentActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionService) CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...client.CallOption) (*DouyinCommentListResponse, error) {
	req := c.c.NewRequest(c.name, "ActionService.CommentList", in)
	out := new(DouyinCommentListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ActionService service

type ActionServiceHandler interface {
	FavoriteAction(context.Context, *DouyinFavoriteActionRequest, *DouyinFavoriteActionResponse) error
	FavoriteList(context.Context, *DouyinFavoriteListRequest, *DouyinFavoriteListResponse) error
	CommentAction(context.Context, *DouyinCommentActionRequest, *DouyinCommentActionResponse) error
	CommentList(context.Context, *DouyinCommentListRequest, *DouyinCommentListResponse) error
}

func RegisterActionServiceHandler(s server.Server, hdlr ActionServiceHandler, opts ...server.HandlerOption) error {
	type actionService interface {
		FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, out *DouyinFavoriteActionResponse) error
		FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, out *DouyinFavoriteListResponse) error
		CommentAction(ctx context.Context, in *DouyinCommentActionRequest, out *DouyinCommentActionResponse) error
		CommentList(ctx context.Context, in *DouyinCommentListRequest, out *DouyinCommentListResponse) error
	}
	type ActionService struct {
		actionService
	}
	h := &actionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ActionService{h}, opts...))
}

type actionServiceHandler struct {
	ActionServiceHandler
}

func (h *actionServiceHandler) FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, out *DouyinFavoriteActionResponse) error {
	return h.ActionServiceHandler.FavoriteAction(ctx, in, out)
}

func (h *actionServiceHandler) FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, out *DouyinFavoriteListResponse) error {
	return h.ActionServiceHandler.FavoriteList(ctx, in, out)
}

func (h *actionServiceHandler) CommentAction(ctx context.Context, in *DouyinCommentActionRequest, out *DouyinCommentActionResponse) error {
	return h.ActionServiceHandler.CommentAction(ctx, in, out)
}

func (h *actionServiceHandler) CommentList(ctx context.Context, in *DouyinCommentListRequest, out *DouyinCommentListResponse) error {
	return h.ActionServiceHandler.CommentList(ctx, in, out)
}
